// import React, { Component } from 'react'
// import { drizzleConnect } from 'drizzle-react'
// import PropTypes from 'prop-types'
// import Logo from '../basics/Logo'
// import { Flex, Box } from '@rebass/grid'
// import Text from '../basics/Text'
// import Split from '../layout/Split'
// import VBackground from '../basics/VBackground'
//import { autoBind } from 'react-extras'
